"""
Components Library for FastHTML.

A Python component library following atomic design principles for FastHTML applications.
Includes design system tokens, pre-built components, and utilities for building
consistent, accessible UIs.

Example usage:
    from components_library import button, card, heading, base_page
    from components_library.design_system import Colors, Spacing

    # Create a page
    page = base_page(
        card(
            heading("Welcome", level=1),
            button("Click me", variant="solid", color_palette="brand")
        ),
        title="Labs App"
    )
"""

# API Client
from .api import (
    ApiClientProtocol,
    ApiError,
    ApiFailure,
    ApiResponse,
    ApiSuccess,
)

# Components - Atoms
from .components.atoms import (
    ICON_ACTIVITY,
    ICON_ALERT_TRIANGLE,
    ICON_ARROW_LEFT,
    ICON_ARROW_RIGHT,
    ICON_CALENDAR,
    ICON_CHECK,
    ICON_CHEVRON_DOWN,
    ICON_CHEVRON_UP,
    ICON_CLOCK,
    ICON_DNA,
    ICON_DOWNLOAD,
    ICON_EXTERNAL_LINK,
    ICON_FILE,
    ICON_FILTER,
    ICON_FLASK,
    ICON_INFO,
    ICON_INFO_FILLED,
    ICON_LOGOUT,
    ICON_MINUS,
    ICON_PAPERCLIP,
    ICON_PLUS,
    ICON_REFRESH,
    ICON_REGISTRY,
    ICON_SEARCH,
    ICON_SETTINGS,
    ICON_SORT,
    ICON_TARGET,
    ICON_USER,
    ICON_X,
    IconName,
    accordion,
    accordion_item,
    alert,
    autocomplete_input,
    avatar,
    badge,
    box,
    button,
    button_link,
    card,
    checkbox,
    chip_select,
    collapsible,
    confidence_score,
    date_input,
    empty_state,
    field,
    flex,
    grid,
    heading,
    hstack,
    icon,
    icon_button,
    input,
    link,
    logical_operator,
    logo,
    menu,
    menu_divider,
    menu_item,
    modal,
    pagination,
    popover,
    progress,
    radio,
    responsive_text,
    select,
    separator,
    skeleton,
    slider,
    spinner,
    svg_icon,
    switch,
    tab_panel,
    table,
    tabs,
    tag,
    text,
    textarea,
    tooltip,
    vstack,
)

# Components - Molecules
from .components.molecules import (
    BackgroundJob,
    BreadcrumbItem,
    FilterGroup,
    TagItem,
    Token,
    UserAction,
    action_card,
    auth_form,
    breadcrumbs,
    date_range_inputs,
    detail_row,
    details_section,
    enhanced_search_bar,
    error_fallback,
    favorite_button,
    file_dropzone,
    file_upload_progress,
    filter_bar,
    filter_panel,
    footer,
    form_modal,
    htmx_file_dropzone,
    htmx_pagination,
    htmx_tag_manager,
    item_details,
    job_status_banner,
    loading_screen,
    overflow_tooltip,
    result_card,
    search_bar,
    search_results,
    tab_state_wrapper,
    tag_manager,
    token_pill,
    user_actions,
    user_nav,
)

# Components - Organisms
from .components.organisms import (
    ArticlesSearchState,
    NotificationItem,
    NotificationTag,
    SearchToken,
    alphabet_browser,
    articles_search,
    concept_suggestions_partial,
    data_table,
    header,
    navigation,
    notifications,
    page_header,
    selected_tokens_partial,
)

# Components - Templates
from .components.templates import (
    BadgeConfig,
    auth_page_layout,
    base_page,
    centered_content,
    error_template,
    labs_intro_page,
    page_container,
    sidebar_layout,
    ui_showcase_page,
)

# Design System
from .design_system import (
    BorderRadius,
    BorderWidth,
    Breakpoints,
    Colors,
    Shadows,
    Spacing,
    Transitions,
    Typography,
    ZIndex,
    base_styles,
    component_styles,
    htmx_config,
    htmx_script,
    menu_click_outside_script,
)

# Services
from .services import (
    ArticleResult,
    ArticleSearchResults,
    Concept,
    ConceptsService,
    DocumentsService,
    SearchQuery,
    SortType,
    SourceType,
    StudyResult,
    csv_response,
    generate_csv,
    register_health_routes,
)

# Utilities
from .utils import (
    SessionToken,
    add_session_token,
    clear_session_tokens,
    color_value,
    confirm_delete,
    debounced_search,
    focus_ring_styles,
    font_size_value,
    generate_border_radius,
    generate_box_shadow,
    generate_style_string,
    get_session_tokens,
    get_size_class,
    get_variant_class,
    htmx_attrs,
    merge_classes,
    modal_trigger,
    remove_session_token,
    responsive_gap,
    set_session_tokens,
    spacing_value,
    toggle_session_operator,
)

__version__ = "0.1.0"

__all__ = [
    "ICON_ACTIVITY",
    "ICON_ALERT_TRIANGLE",
    "ICON_ARROW_LEFT",
    "ICON_ARROW_RIGHT",
    "ICON_CALENDAR",
    "ICON_CHECK",
    "ICON_CHEVRON_DOWN",
    "ICON_CHEVRON_UP",
    "ICON_CLOCK",
    "ICON_DNA",
    "ICON_DOWNLOAD",
    "ICON_EXTERNAL_LINK",
    "ICON_FILE",
    "ICON_FILTER",
    "ICON_FLASK",
    "ICON_INFO",
    "ICON_INFO_FILLED",
    "ICON_LOGOUT",
    "ICON_MINUS",
    "ICON_PAPERCLIP",
    "ICON_PLUS",
    "ICON_REFRESH",
    "ICON_REGISTRY",
    "ICON_SEARCH",
    "ICON_SETTINGS",
    "ICON_SORT",
    "ICON_TARGET",
    "ICON_USER",
    "ICON_X",
    # API Client
    "ApiClientProtocol",
    "ApiError",
    "ApiFailure",
    "ApiResponse",
    "ApiSuccess",
    # Services - Models
    "ArticleResult",
    "ArticleSearchResults",
    # Data classes - Organisms
    "ArticlesSearchState",
    # Auth
    "Auth0Service",
    # Data classes - Molecules
    "BackgroundJob",
    # Data classes - Templates
    "BadgeConfig",
    # Design System - Tokens
    "BorderRadius",
    "BorderWidth",
    "BreadcrumbItem",
    "Breakpoints",
    "Colors",
    "Concept",
    # Services - Classes
    "ConceptsService",
    "DocumentsService",
    "FilterGroup",
    "IconName",
    "NotificationItem",
    "NotificationTag",
    "SearchQuery",
    "SearchToken",
    "SessionToken",
    "Shadows",
    "SortType",
    "SourceType",
    "Spacing",
    "StudyResult",
    "TagItem",
    "Token",
    "Transitions",
    "Typography",
    "User",
    "UserAction",
    "ZIndex",
    # Version
    "__version__",
    # Atoms
    "accordion",
    "accordion_item",
    # Molecules
    "action_card",
    # Session utilities
    "add_session_token",
    "alert",
    # Organisms
    "alphabet_browser",
    "articles_search",
    "auth_form",
    # Templates
    "auth_page_layout",
    "autocomplete_input",
    "avatar",
    "badge",
    "base_page",
    # Design System - Theme
    "base_styles",
    "box",
    "breadcrumbs",
    "button",
    "button_link",
    "card",
    "centered_content",
    "checkbox",
    "chip_select",
    "clear_session_tokens",
    "collapsible",
    # Utilities
    "color_value",
    "component_styles",
    "concept_suggestions_partial",
    "confidence_score",
    "confirm_delete",
    # Services - Functions
    "csv_response",
    "data_table",
    "date_input",
    "date_range_inputs",
    "debounced_search",
    "detail_row",
    "details_section",
    "empty_state",
    "enhanced_search_bar",
    "error_fallback",
    "error_template",
    "favorite_button",
    "field",
    "file_dropzone",
    "file_upload_progress",
    "filter_bar",
    "filter_panel",
    "flex",
    "focus_ring_styles",
    "font_size_value",
    "footer",
    "form_modal",
    "generate_border_radius",
    "generate_box_shadow",
    "generate_csv",
    "generate_style_string",
    "get_access_token",
    "get_current_user",
    "get_labs_dashboard_url",
    "get_session_tokens",
    "get_size_class",
    "get_variant_class",
    "grid",
    "header",
    "heading",
    "hstack",
    "htmx_attrs",
    "htmx_config",
    "htmx_file_dropzone",
    "htmx_pagination",
    "htmx_script",
    "htmx_tag_manager",
    "icon",
    "icon_button",
    "input",
    "is_authenticated",
    "item_details",
    "job_status_banner",
    "labs_intro_page",
    "link",
    "loading_screen",
    "logical_operator",
    "logo",
    "menu",
    "menu_click_outside_script",
    "menu_divider",
    "menu_item",
    "merge_classes",
    "modal",
    "modal_trigger",
    "navigation",
    "notifications",
    "overflow_tooltip",
    "page_container",
    "page_header",
    "pagination",
    "popover",
    "progress",
    "radio",
    "register_health_routes",
    "remove_session_token",
    "responsive_gap",
    "responsive_text",
    "result_card",
    "search_bar",
    "search_results",
    "select",
    "selected_tokens_partial",
    "separator",
    "set_session_tokens",
    "sidebar_layout",
    "skeleton",
    "slider",
    "spacing_value",
    "spinner",
    "svg_icon",
    "switch",
    "tab_panel",
    "tab_state_wrapper",
    "table",
    "tabs",
    "tag",
    "tag_manager",
    "text",
    "textarea",
    "toggle_session_operator",
    "token_pill",
    "tooltip",
    "ui_showcase_page",
    "user_actions",
    "user_nav",
    "vstack",
]
